name: layout_manager
description: Helper
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  parse_server_sdk: ^5.1.3
  firebase_core: ^2.15.1
  firebase_remote_config: ^4.2.5
  shared_preferences: ^2.2.0
  webview_flutter: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.layout_manager.layout_manager
        pluginClass: LayoutManagerPlugin
      ios:
        pluginClass: LayoutManagerPlugin
      windows:
        pluginClass: LayoutManagerPluginCApi
